### ISSUE TITLE
Shows error after updating to 1.1.3 version

### ISSUE THREAD

**Issue by sasha240100** [borisirota/webworkify-webpack#14]
![image](https://cloud.githubusercontent.com/assets/7657429/16853044/6bd12616-4a13-11e6-913d-cf5e7f5237de.png)
Here is what i've got in my console after updating to `1.1.3` (last error). Moving to `1.1.2` solved this problem.

**Comment by austinhyde** [comment]
What does your code look like where you invoke `webworkify-webpack`? And what's the function you're running with it?

**Comment by sasha240100** [comment]
@austinhyde 
 Look at this two files: https://github.com/WhitestormJS/whitestorm.js/blob/master/src/physics/core/scene.js#L23
https://github.com/WhitestormJS/whitestorm.js/blob/master/webpack.config.babel.js#L27

**Comment by austinhyde** [comment]
Interesting... I don't see anything obvious. If you're willing to do a little extra debugging, could you switch back to v1.1.3, open your node_modules/webworkify-webpack/index.js and put a `debugger;` on [line 34](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L34)?

The issue that the condition on [line 46](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L46) is never matching, so it can't find the module that contains the [WhitestormJS worker factory](https://github.com/WhitestormJS/whitestorm.js/blob/master/src/physics/worker.js#L3).

To figure out why, I need to see the first few lines of `fn.toString()`, `fnString`, and the stringified version of whatever module corresponds to that worker factory (`sources[k].toString()`). The catch is that I can't tell you what that `k` is, as it will be unique to your webpack build, so you'll need to poke through the `sources` list and find the module manually, then run `.toString()` on that function.

Something like `sources.findIndex(m => m.toString().indexOf('transferableMessage = self.webkitPostMessage || self.postMessage') > -1)` should work while you're paused on that debugger breakpoint, although you may need to tweak the string you're looking for if that doesn't match, or if WhitestormJS is minified.

**Comment by sasha240100** [comment]
@austinhyde You may clone that repo, then:
1. `npm install`
2. Change **webworkify-webpack** version to 1.1.3 (current is 1.1.2).  
3. `gulp dev` (and wait until webpack will finish build)
4. Then go to `localhost:8080/` and you will a list of examples. Choose any and you will see that error.

**Comment by borisirota** [comment]
@austinhyde thanks !

@sasha240100 in the meanwhile just name the function you pass to `webworkify-webpack` as noted in the [second caveat](https://github.com/borisirota/webworkify-webpack#caveats) and it should work.

**Comment by austinhyde** [comment]
@borisirota I figure I broke it, so I get to fix it :) Interestingly, the issue appears to be that `wrapperFuncString` contains `function (self) {`, whereas `fnString` gets mangled to `function(self) {` (without the space between `function` and `(`.

Which means that, after my changes from #13, `.replace(/^function\s?\((.*)\)(\s?)\{(\n"use strict";\n)?/, 'function($1)$2{')` would basically just go away, but since obviously other browsers need that mangling... I'm going to try to search for the function based on a regex instead of mangling `fn.toString()`

**Comment by borisirota** [comment]
@sasha240100 should be fixed in version 1.1.4. Can you verify it please ?

**Comment by sasha240100** [comment]
@borisirota Will check it today

**Comment by borisirota** [comment]
@sasha240100 any updates ? can I close this issue ?

**Comment by sasha240100** [comment]
@borisirota not yet. Sorry, had no time( I will try 1.1.4 these days. Btw, what is new in this version?

**Comment by borisirota** [comment]
@sasha240100 [this PR](https://github.com/borisirota/webworkify-webpack/pull/15)

**Comment by borisirota** [comment]
@sasha240100 I'm closing this issue. Feel free to reopen if you encounter this again.
