### ISSUE TITLE
Provide documentation details on difference between this and webpack's target: 'webworker'

### ISSUE THREAD

**Issue by TheLarkInn** [borisirota/webworkify-webpack#19]
I was wondering if it would be possible that you provide some information on how using this vs webpack's built in `target: 'webworker'` differs. 

It could provide users with multiple options or justifications for using one over the other. Plus if some of the things this library is trying to accomplish can be done through the webpack `target: 'webworker'`, then we should get a PR in for the sake of updating that section of our core codebase!! Excellent work and thank you for the contributions to the webpack community.

**Comment by borisirota** [comment]
Sure. I'll do it soon. Thanks.

**Comment by borisirota** [comment]
@TheLarkInn done in v2. checkout the README. Please let me know if you think something is missing. thanks !
