### ISSUE TITLE
This library is awesome

### ISSUE THREAD

**Issue by ekeric13** [borisirota/webworkify-webpack#23]
The webpack [worker loader](https://github.com/webpack/worker-loader) is extremely confusing to set up, and on top of that [the examples](https://github.com/webpack/webpack/tree/master/examples/web-worker) are for webpack 2 only and aren't backwards compatible for webpack 1 and don't mention this fact anywhere.

It could just be I find webpack loaders confusing in general but this is much easier.

It must work by creating an inline web worker, correct? Since it doesn't require you to make an extra script tag or anything.

**Comment by borisirota** [comment]
Thanks :)

Yes. It creates the worker in runtime from the existing modules. Its possible to make inline worker with the `worker-loader` as well but it means that there will be duplications if same code runs in both web and worker environments.

You can see the [comparison section](https://github.com/borisirota/webworkify-webpack#webworkify-webpack-vs-webpacks-worker-loader-and-target-webworker) in README.
