### ISSUE TITLE
Uncaught TypeError: (intermediate value) ...  is not a function

### ISSUE THREAD

**Issue by JimmyVV** [borisirota/webworkify-webpack#32]
When I use these codes like you explaininig, the process is normal, but it will alwasy throw a error:

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function
```

and, my codes are:

```
this._worker = worker(require.resolve('./chunks.worker'));
```
the fakeCode of chunks.worker.js is:

```
import xx from "xxx";

class WorkerController{
    // ...
}

new WorkerController;
```

**Comment by JimmyVV** [comment]
the screenshot is:

![error](http://villainhr-1252111119.file.myqcloud.com/Screen%20Shot%202018-01-28%20at%2023.49.08.png)

**Comment by borisirota** [comment]
Hi @JimmyVV you should export a function as default from `chunks.worker.js` like in the [example](https://github.com/borisirota/webworkify-webpack/blob/master/example/es6-worker.js#L3)

**Comment by JimmyVV** [comment]
Yeah, I have already resolved it. Thanks very much.
