### ISSUE TITLE
webpack 4 support

### ISSUE THREAD

**Issue by egoroof** [borisirota/webworkify-webpack#33]
Looks like this isn't compatible with webpack 4 which is already in beta. Do you plan to support it?

**Comment by borisirota** [comment]
Hi @egoroof Just getting back to business after a long vacation so still didn't check in depth the differences between webpack versions but yes it will be compatible.  
Anyway, I took a snap look at the new webpack output and I don't see API changes which should affect `webworkify-webpack`.  
Can you please paste the output of your bundle ? what error are you getting ? Any additional info will help :)

**Comment by egoroof** [comment]
Found the problem and send a PR #35
