### ISSUE TITLE
Spawning child workers

### ISSUE THREAD

**Issue by mcnuttandrew** [borisirota/webworkify-webpack#34]
I'm having some trouble getting workers created through `webworkify-webpack` to spawn child  workers. Is this supported functionality? Alternatively, am I being dumb: Inside of my initial worker i have code:

```
import work from 'webworkify-webpack';
const aggWorker = work(require.resolve('./agg-worker.js'));
```
Which then gives a "Uncaught ReferenceError: window is not defined" error in chrome. Thanks

**Comment by borisirota** [comment]
Hi @mcnuttandrew, basically I haven't tried it but it can be supported. Currently the access to all relevant globals are through the window object ([here](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L173), [here](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L176) and [here](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L179)) which isn't defined in web worker context. Replacing `window` with `self` will make it work in web worker too and should allow the spawning of child workers.

But, you need to be aware that due too a bug, [sub workers aren't supported in chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=31666) for quite a long time. There is [a polyfill](https://github.com/dmihal/Subworkers) so you can play with it to check if it works for you.

I'm happy to receive a PR if support for sub workers can help you :)
