### ISSUE TITLE
webworkify_webpack_1.default is not a function

### ISSUE THREAD

**Issue by sky0014** [borisirota/webworkify-webpack#36]
I used it as the example said:
```js
import worker from "webworkify-webpack";
let w = worker(require.resolve("./worker"));
```

It seems that it's not compatible with es6 module.

**Comment by borisirota** [comment]
Which webpack version do you use?

**Comment by sky0014** [comment]
webpack@2.5.1

**Comment by borisirota** [comment]
I have tested with webpack@2.5.1 and everything works as expected.

Do you still have the issue? If so, please show me the contents of "./worker".

**Comment by sky0014** [comment]
@borisirota My fault, I use the wrong version. :joy: , I'll close this issue, thank you.
