### ISSUE TITLE
String matching for functions.

### ISSUE THREAD

**Issue by KGan** [borisirota/webworkify-webpack#9]
https://github.com/borisirota/webworkify-webpack/commit/7996812dcfa194835980332015715db8145f7234

string matching here won't work if the worker file defines its export function without a space, since the toString will always inject a space. Will happen very often with code minifiers.
`(function(e){}).toString() // produces "function (e){}"`

**Comment by borisirota** [comment]
A quick fix will be to name the anonymous function (and make sure there is no white space between the name and the parenthesis => `(function a (e){}).toString() // produces "function a(e){}"`). It doesn't seem like I can do here something. Any ideas ?

I added this to the caveats section in the README so I'm closing it unless there will be some idea.

Thanks !

**Comment by borisirota** [comment]
@KGan Should be fixed in version `1.1.1` with #11
